### ISSUE TITLE
pretrained model

### ISSUE THREAD

**Issue by wait1988** [d-li14/face-attribute-prediction#1]
Can you provide the pretrained model for test?

**Comment by d-li14** [comment]
Pre-trained models will be released later. Now you can easily get the checkpoints due to fast convergence.

**Comment by mazzzystar** [comment]
@d-li14 Any plans to release the pre-trained models ?

**Comment by Oktai15** [comment]
@d-li14 any update to this issue?

**Comment by ainrichman** [comment]
预训练模型放出来看个demo呗
